# Generated by Django 4.2.1 on 2023-11-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Task', max_length=100, verbose_name='Task')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Description of task')),
            ],
        ),
    ]
